/controller_node:
  ros__parameters:
    torpedo_fin: 3
    vehicle_name: auv0

/command_node:
  ros__parameters:
    random: false
    deep: true

/command_coop_node:
  ros__parameters:
    random: false
    deep: true
    uav_command_topic: uav_command
    sv_command_topic: sv_command